spring.application.name=@app.name@


#spring.datasource.h2.url=jdbc:h2:mem:assessdb
#spring.datasource.h2.driverClassName=org.h2.Driver
#spring.datasource.h2.username=sa
#spring.datasource.h2.password=sa

spring.datasource.h2.jdbc-url=jdbc:h2:mem:assessdb
spring.datasource.h2.driver-class-name=org.h2.Driver
spring.datasource.h2.username=sa
spring.datasource.h2.password=sa




spring.datasource.mysql.jdbc-url=jdbc:mysql://localhost:3306/assessment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.mysql.username=root
spring.datasource.mysql.password=root
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2

# HikariCP settings
spring.datasource.hikari.minimumIdle=3
spring.datasource.hikari.maximumPoolSize=40
spring.datasource.hikari.idleTimeout=12000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=6000
spring.datasource.hikari.poolName=HikariPool_ASSESSMENT

logging.level.org.springframework.web=info

management.endpoints.web.exposure.include= health,info,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.server.port=7179

server.tomcat.accept-count=15
server.tomcat.threads.max=10